### ISSUE TITLE
alevin-fry quant --resolution cr-like-em hangs in rare cases

### ISSUE THREAD

**Issue by jashapiro** [COMBINE-lab/radicl#28]
We have started running many samples through the alevin-fry pipeline, and were starting to run more tests with the `cr-like-em` resolution strategy, and encountered the following error in one case (so far!): 

```
thread '<unnamed>' panicked at 'Alpha Sum too small', libradicl/src/em.rs:218:5
stack backtrace:
   0: std::panicking::begin_panic
   1: libradicl::em::em_optimize_subset
   2: libradicl::quant::do_quantify::{{closure}}
```
This was followed by alevin-fry appearing to hang, rather than exiting with an error. (CPU usage remained high for at least one thread)

The command used (with directories redacted) was: 
```
alevin-fry quant --input-dir {in} --tg-map index.tx2gene_3col.tsv --resolution cr-like-em  -o {out} --use-mtx -t 2
```

I tried again with only a single thread and got the same error. Increasing the number of threads resulted in more chunks being processed (and continuing after the panic), but the process still hung before completion. 

`--resolution cr-like` worked as expected.

This error occurred using alevin-fry version 0.4.1, both running directly on MacOS 11.6 and using the BioContainers Docker image (on an Ubuntu 20.04 system).

If there are other tests that I can help with, I would be happy to do so. 

An example full command output with a full backtrace is included below:
```
2021-10-12 14:28:03 INFO quantifying from uncompressed, collated RAD file File { fd: 4, path: "[redacted]/map.collated.rad", read: true, write: false }
2021-10-12 14:28:03 INFO paired : false, ref_count : 625,428, num_chunks : 94,306
2021-10-12 14:28:03 INFO tg-map contained 60,319 genes mapping to 625,428 transcripts.
2021-10-12 14:28:03 INFO read 2 file-level tags
2021-10-12 14:28:03 INFO read 2 read-level tags
2021-10-12 14:28:03 INFO read 1 alignemnt-level tags
2021-10-12 14:28:03 INFO File-level tag values FileTags { bclen: 16, umilen: 12 }
⠤ [00:00:26] [╢╢╢╢╢╢░╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟╟]   14462/94306
thread '<unnamed>' panicked at 'Alpha Sum too small', libradicl/src/em.rs:218:5
stack backtrace:
   0:        0x100f38933 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b5b7de1c79b4b45
   1:        0x100de2f8e - core::fmt::write::h65ec8c8a6aa7b549
   2:        0x100f3637a - std::io::Write::write_fmt::hc52e560ab9e57db4
   3:        0x100f3caff - std::panicking::default_hook::{{closure}}::h0974624c30a6e2b5
   4:        0x100f3d360 - std::panicking::rust_panic_with_hook::h1cdaa4b48d8ea4a1
   5:        0x100e1c32d - std::panicking::begin_panic::{{closure}}::h5fb64ee7ea289a2a
   6:        0x100e199c8 - std::sys_common::backtrace::__rust_end_short_backtrace::ha5d99a8c5039d801
   7:        0x100fd357d - std::panicking::begin_panic::hd38a6e223ccbb64a
   8:        0x100e57ccb - libradicl::em::em_optimize_subset::h536b75956bd94226
   9:        0x100e22b7b - libradicl::quant::do_quantify::{{closure}}::h91f63fc336437966
  10:        0x100e199fb - std::sys_common::backtrace::__rust_begin_short_backtrace::h266e2e2ef561fccd
  11:        0x100e1c728 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2e45eb7f25374de8
  12:        0x100f409bd - std::sys::unix::thread::Thread::new::thread_start::h59fdfe326de12d08
  13:     0x7fff204f78fc - __pthread_start
```

**Comment by rob-p** [comment]
Hi @jashapiro,

   We've published 0.4.2.  Could you guys give this a try when you have a chance?

Thanks,
Rob
